FROM python:3.8
LABEL maintainer="TelegramGithubBot"

ADD GithubBot/main.py /
ADD GithubBot/keys.py /
ADD GithubBot/grouplist.txt /

RUN pip3 install -r requirements.txt

CMD [ "python3", "./main.py" ]